services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_FEATURES: token-exchange
    ports:
      - "8080:8080"
    command: start-dev

  mysql:
    image: mysql:8.0
    container_name: mormanno-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mormannoshop
      MYSQL_USER: mormanno
      MYSQL_PASSWORD: mormannopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mormanno-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  mysql_data:

networks:
  mormanno-network:
    driver: bridge