services:
  mysql:
    image: mysql:8.0
    container_name: mormanno-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mormannoshop
      MYSQL_USER: mormanno
      MYSQL_PASSWORD: mormannopassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mormanno-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  mysql_data:

networks:
  mormanno-network:
    driver: bridge